# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/meta-optimizer',
                'doc_host': 'https://valueanalyticslabs.github.io',
                'git_url': 'https://github.com/valueanalyticslabs/meta-optimizer',
                'lib_path': 'meta_optimizer'},
  'syms': { 'meta_optimizer\\core': { 'meta_optimizer\\core.foo': ( 'https://valueanalyticslabs.github.io/core.html#foo',
                                                                    'https://github.com/valueanalyticslabs/meta-optimizer/blob/master/meta_optimizer\\core.py#L7')}}}